import { MigrationInterface, QueryRunner } from "typeorm";
export class CrawlSources1710000005000 implements MigrationInterface {
  name = "CrawlSources1710000005000";
  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TABLE "crawl_sources" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "name" varchar(160) NOT NULL, "domain" varchar(255) NOT NULL UNIQUE, "type" varchar(20) NOT NULL CHECK ("type" IN ('news','policy','rss','sitemap')), "fetch_method" varchar(20) NOT NULL CHECK ("fetch_method" IN ('html','rss','sitemap','adapter')), "schedule_minutes" integer NOT NULL DEFAULT 360 CHECK ("schedule_minutes" >= 5), "trust_level" smallint NOT NULL DEFAULT 3 CHECK ("trust_level" BETWEEN 1 AND 5), "authorization_status" varchar(20) NOT NULL DEFAULT 'pending' CHECK ("authorization_status" IN ('pending','authorized','restricted','rejected')), "is_enabled" boolean NOT NULL DEFAULT false, "keywords" jsonb NOT NULL DEFAULT '[]'::jsonb, "entry_url" varchar(1000), "last_crawled_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now())`);
    await q.query(`CREATE INDEX "IDX_crawl_sources_ready" ON "crawl_sources" ("is_enabled", "authorization_status")`);
    await q.query(`CREATE TABLE "crawl_jobs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "source_id" uuid NOT NULL REFERENCES "crawl_sources"("id") ON DELETE CASCADE, "status" varchar(20) NOT NULL DEFAULT 'queued' CHECK ("status" IN ('queued','running','succeeded','failed')), "queue_key" varchar(100) NOT NULL, "started_at" timestamptz, "finished_at" timestamptz, "duration_ms" integer, "discovered_count" integer NOT NULL DEFAULT 0, "error_message" text, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now())`);
    await q.query(`CREATE INDEX "IDX_crawl_jobs_source" ON "crawl_jobs" ("source_id", "created_at" DESC)`);
    await q.query(`CREATE TABLE "crawl_logs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "job_id" uuid NOT NULL REFERENCES "crawl_jobs"("id") ON DELETE CASCADE, "level" varchar(10) NOT NULL CHECK ("level" IN ('info','warning','error')), "message" text NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" timestamptz NOT NULL DEFAULT now())`);
    await q.query(`CREATE INDEX "IDX_crawl_logs_job" ON "crawl_logs" ("job_id", "created_at")`);
    await q.query(`INSERT INTO "crawl_sources" ("name", "domain", "type", "fetch_method", "schedule_minutes", "trust_level", "authorization_status", "is_enabled", "keywords", "entry_url") VALUES ('本地采集测试页', '127.0.0.1', 'news', 'html', 30, 5, 'authorized', false, '["OPC 一人公司","OPC财经","OPC超级个体","一人公司","超级个体","个体创业","创业扶持","小微企业","专精特新","数字经济","人工智能","普惠金融","减税降费","营商环境"]'::jsonb, 'http://127.0.0.1:8099/article.html')`);
  }
  async down(q: QueryRunner): Promise<void> { await q.query(`DROP TABLE IF EXISTS "crawl_logs"`); await q.query(`DROP TABLE IF EXISTS "crawl_jobs"`); await q.query(`DROP TABLE IF EXISTS "crawl_sources"`); }
}
