import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { CreatorAccount } from "../database/entities/creator-account.entity";
import { AuthorizationStatus, Creator } from "../database/entities/creator.entity";
import { SubtitleStatus, Video } from "../database/entities/video.entity";
import { VideoSyncLog } from "../database/entities/video-sync-log.entity";
import { CreateCreatorAccountDto } from "./dto/create-creator-account.dto";
import { CreateCreatorDto } from "./dto/create-creator.dto";
import { ListVideosDto } from "./dto/list-videos.dto";
import { UpdateSubtitleDto } from "./dto/update-subtitle.dto";
import { LocalMockVideoAdapter } from "./video-discovery.adapter";
@Injectable()
export class VideosService { constructor(@InjectRepository(Creator) private readonly creators: Repository<Creator>, @InjectRepository(CreatorAccount) private readonly accounts: Repository<CreatorAccount>, @InjectRepository(Video) private readonly videos: Repository<Video>, @InjectRepository(VideoSyncLog) private readonly syncLogs: Repository<VideoSyncLog>) {}
  async list(input: ListVideosDto) { const query = this.videos.createQueryBuilder("video").leftJoinAndSelect("video.creatorAccount", "account").leftJoinAndSelect("account.creator", "creator").where("video.is_published = true"); if (input.platform) query.andWhere("video.platform = :platform", { platform: input.platform }); if (input.industry) query.andWhere(":industry = ANY (SELECT jsonb_array_elements_text(creator.industries))", { industry: input.industry }); query.orderBy(input.sort === "hot" ? "(COALESCE((video.platform_metrics->>'views')::int,0) + COALESCE((video.platform_metrics->>'likes')::int,0)*10)" : "video.published_at", "DESC"); return query.take(60).getMany(); }
  listCreators() { return this.creators.find({ relations: { accounts: true }, order: { trustLevel: "DESC", name: "ASC" } }); }
  async createCreator(input: CreateCreatorDto) { const status = input.authorizationStatus ?? AuthorizationStatus.PENDING; if (input.isEnabled && status !== AuthorizationStatus.AUTHORIZED) throw new BadRequestException("只有已授权创作者可以启用"); return this.creators.save(this.creators.create({ ...input, name: input.name.trim(), avatarUrl: input.avatarUrl ?? null, industries: input.industries ?? [], authorizationStatus: status, isEnabled: input.isEnabled ?? false })); }
  async createAccount(input: CreateCreatorAccountDto) { const creator = await this.creators.findOneBy({ id: input.creatorId }); if (!creator) throw new NotFoundException("创作者不存在"); if (input.isEnabled && (!creator.isEnabled || creator.authorizationStatus !== AuthorizationStatus.AUTHORIZED)) throw new BadRequestException("创作者未获授权或未启用"); return this.accounts.save(this.accounts.create({ ...input, creator, isEnabled: input.isEnabled ?? false })); }
  async syncLocal(accountId: string) { const account = await this.accounts.findOne({ where: { id: accountId }, relations: { creator: true } }); if (!account || !account.isEnabled || !account.creator.isEnabled || account.creator.authorizationStatus !== AuthorizationStatus.AUTHORIZED) throw new BadRequestException("账号未获授权或未启用"); const adapter = new LocalMockVideoAdapter(); try { const found = await adapter.discover(accountId); let count = 0; for (const item of found) { if (await this.videos.exists({ where: { platform: item.platform, platformVideoId: item.platformVideoId } })) continue; await this.videos.save(this.videos.create({ ...item, coverUrl: item.coverUrl, publishedAt: new Date(item.publishedAt), creatorAccount: account })); count++; } await this.syncLogs.save(this.syncLogs.create({ creatorAccount: account, status: "succeeded", discoveredCount: count, errorMessage: null })); return { discoveredCount: count }; } catch (error) { await this.syncLogs.save(this.syncLogs.create({ creatorAccount: account, status: "failed", discoveredCount: 0, errorMessage: error instanceof Error ? error.message : "同步失败" })); throw error; } }
  async updateSubtitle(id: string, input: UpdateSubtitleDto) { const video = await this.video(id); const legal = new Set([SubtitleStatus.AUTHORIZED, SubtitleStatus.PROCESSING, SubtitleStatus.COMPLETED]); if (legal.has(input.status) && video.subtitleStatus === SubtitleStatus.NO_PERMISSION) throw new BadRequestException("无权限字幕不能进入处理流程"); if (input.status === SubtitleStatus.PROCESSING && video.subtitleStatus !== SubtitleStatus.AUTHORIZED) throw new BadRequestException("字幕仅在已授权后可处理"); if (input.status === SubtitleStatus.COMPLETED && (video.subtitleStatus !== SubtitleStatus.PROCESSING || !input.transcript?.trim())) throw new BadRequestException("需要在处理状态下提供合法字幕文本才能完成"); video.subtitleStatus = input.status; if (input.source !== undefined) video.subtitleSource = input.source; if (input.transcript !== undefined) video.transcript = input.transcript; if (input.status === SubtitleStatus.COMPLETED) Object.assign(video, this.videoSummary(input.transcript!)); return this.videos.save(video); }
  async video(id: string) { const video = await this.videos.findOne({ where: { id }, relations: { creatorAccount: { creator: true } } }); if (!video) throw new NotFoundException("视频不存在"); return video; }
  private videoSummary(transcript: string) { const text = transcript.replace(/\s+/g, " ").trim(); const sentences = text.split(/[。！？]/).map((value) => value.trim()).filter(Boolean); return { contentSummary: text.slice(0, 180), keyPoints: sentences.slice(0, 5), industryTags: ["OPC与个体经济", "财经"], chapters: sentences.slice(0, 4).map((title, index) => ({ startSeconds: index * 120, title })), summaryModelVersion: "subtitle-rule-v1" }; }
}
