import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { createHash } from "crypto";
import { Repository } from "typeorm";
import { Article, ArticleStatus, ArticleType } from "../database/entities/article.entity";
import { ArticleSource } from "../database/entities/article-source.entity";
import { ContentKeyword } from "../database/entities/content-keyword.entity";
import { CrawlDiscovery } from "../database/entities/crawl-discovery.entity";
import { CrawlSource } from "../database/entities/crawl-source.entity";
import { LinkCheck } from "../database/entities/link-check.entity";
import { IngestCrawlArticleDto } from "./dto/ingest-crawl-article.dto";

@Injectable()
export class CrawlProcessingService {
  constructor(@InjectRepository(Article) private readonly articles: Repository<Article>, @InjectRepository(ArticleSource) private readonly articleSources: Repository<ArticleSource>, @InjectRepository(CrawlSource) private readonly sources: Repository<CrawlSource>, @InjectRepository(CrawlDiscovery) private readonly discoveries: Repository<CrawlDiscovery>, @InjectRepository(ContentKeyword) private readonly keywords: Repository<ContentKeyword>, @InjectRepository(LinkCheck) private readonly linkChecks: Repository<LinkCheck>) {}
  async saveDiscoveries(sourceId: string, urls: string[]) { const source = await this.sources.findOneBy({ id: sourceId }); if (!source) throw new NotFoundException("采集来源不存在"); const created: CrawlDiscovery[] = []; for (const url of [...new Set(urls)]) { if (!url.startsWith("http")) continue; const existing = await this.discoveries.findOne({ where: { source: { id: sourceId }, url } }); if (!existing) created.push(this.discoveries.create({ source, url, queuedAt: null })); } return this.discoveries.save(created); }
  async ingest(input: IngestCrawlArticleDto) { const source = await this.sources.findOneBy({ id: input.sourceId }); if (!source?.isEnabled) throw new BadRequestException("采集来源不存在或未启用"); const canonicalUrl = input.canonicalUrl ?? input.originalUrl; const fingerprint = this.fingerprint(input.content); const duplicate = await this.articles.createQueryBuilder("article").where("article.canonical_url = :canonicalUrl OR article.content_fingerprint = :fingerprint", { canonicalUrl, fingerprint }).getOne(); if (duplicate) { await this.appendSource(duplicate.id, source.name, input.originalUrl); return { article: duplicate, duplicateOf: duplicate.id }; }
    const classification = await this.classify(`${input.title}\n${input.content}`); const summary = this.summary(input.content); const slug = `crawl-${createHash("sha256").update(canonicalUrl).digest("hex").slice(0, 16)}`; const article = await this.articles.save(this.articles.create({ slug, title: input.title.trim(), content: input.content.trim(), summary: summary.text, summaryKeywords: summary.keywords, summaryEntities: summary.entities, summaryModelVersion: "rule-based-v1", summaryGeneratedAt: new Date(), summaryReviewed: false, type: input.type ?? ArticleType.NEWS, status: ArticleStatus.REVIEW, originalUrl: input.originalUrl, canonicalUrl, contentFingerprint: fingerprint, coverImageUrl: input.coverImageUrl ?? null, publishedAt: input.publishedAt ? new Date(input.publishedAt) : null, classification, sources: [this.articleSources.create({ name: source.name, url: input.originalUrl, isPrimary: true })] })); return { article, duplicateOf: null }; }
  async reviewQueue() { return this.articles.find({ where: { status: ArticleStatus.REVIEW }, relations: { sources: true, category: true, tags: true }, order: { updatedAt: "ASC" }, take: 100 }); }
  async reject(id: string) { const article = await this.article(id); article.status = ArticleStatus.OFFLINE; return this.articles.save(article); }
  async merge(id: string, targetId: string) { if (id === targetId) throw new BadRequestException("不能合并到自身"); const [source, target] = await Promise.all([this.article(id), this.article(targetId)]); const sources = await this.articleSources.find({ where: { article: { id: source.id } } }); for (const item of sources) await this.appendSource(target.id, item.name, item.url); source.status = ArticleStatus.OFFLINE; await this.articles.save(source); return this.articles.findOneOrFail({ where: { id: target.id }, relations: { sources: true } }); }
  async recordLinkCheck(articleId: string, statusCode: number | null, redirectUrl?: string, errorMessage?: string) { await this.article(articleId); const healthy = Boolean(statusCode && statusCode >= 200 && statusCode < 400); return this.linkChecks.save(this.linkChecks.create({ article: { id: articleId } as Article, statusCode, redirectUrl: redirectUrl ?? null, errorMessage: errorMessage ?? null, isHealthy: healthy })); }
  private async article(id: string) { const article = await this.articles.findOneBy({ id }); if (!article) throw new NotFoundException("文章不存在"); return article; }
  private fingerprint(content: string) { return createHash("sha256").update(content.replace(/\s+/g, "").toLowerCase()).digest("hex"); }
  private async appendSource(articleId: string, name: string, url: string) { const exists = await this.articleSources.exists({ where: { article: { id: articleId }, url } }); if (!exists) await this.articleSources.save(this.articleSources.create({ article: { id: articleId } as Article, name, url, isPrimary: false })); }
  private async classify(text: string) { const terms = await this.keywords.find({ where: { isActive: true } }); const result: Record<string, number> = {}; for (const term of terms) if (text.includes(term.keyword)) result[term.industry] = (result[term.industry] ?? 0) + Number(term.weight); const total = Object.values(result).reduce((sum, value) => sum + value, 0); return Object.fromEntries(Object.entries(result).map(([key, value]) => [key, Math.round((value / total) * 100) / 100])); }
  private summary(content: string) { const text = content.replace(/\s+/g, " ").trim().slice(0, 160); const keywords = [...new Set(content.match(/[\u4e00-\u9fa5]{2,8}/g) ?? [])].slice(0, 5); const entities = [...new Set(content.match(/[A-Z][A-Za-z0-9& -]{2,30}/g) ?? [])].slice(0, 5); return { text, keywords, entities }; }
}
