import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { ILike, Repository } from "typeorm";
import { AuthUser } from "../auth/auth-user.interface";
import { EventRegistration, EventRegistrationStatus } from "../database/entities/event-registration.entity";
import { Event, EventStatus } from "../database/entities/event.entity";
import { NotificationType } from "../database/entities/notification.entity";
import { User } from "../database/entities/user.entity";
import { NotificationsService } from "../notifications/notifications.service";
import { CreateEventDto } from "./dto/create-event.dto";
import { ListEventsDto } from "./dto/list-events.dto";
import { RegisterEventDto } from "./dto/register-event.dto";
import { UpdateEventDto } from "./dto/update-event.dto";
import { UpdateRegistrationDto } from "./dto/update-registration.dto";

@Injectable()
export class EventsService {
  constructor(@InjectRepository(Event) private readonly events: Repository<Event>, @InjectRepository(EventRegistration) private readonly registrations: Repository<EventRegistration>, private readonly notifications: NotificationsService) {}
  async list(input: ListEventsDto, includeUnpublished = false) { const where: Record<string, unknown> = {}; if (includeUnpublished && input.status) where.status = input.status; if (!includeUnpublished) where.status = EventStatus.PUBLISHED; if (input.q) where.title = ILike(`%${input.q.trim()}%`); const [items, total] = await this.events.findAndCount({ where, relations: { organizer: true }, order: { startsAt: "ASC" }, skip: (input.page - 1) * input.limit, take: input.limit }); return { items: await Promise.all(items.map((event) => this.view(event))), pagination: { page: input.page, limit: input.limit, total, totalPages: Math.ceil(total / input.limit) } }; }
  async detail(id: string, includeUnpublished = false) { const event = await this.events.findOne({ where: includeUnpublished ? { id } : { id, status: EventStatus.PUBLISHED }, relations: { organizer: true } }); if (!event) throw new NotFoundException("活动不存在或暂不可见"); return this.view(event); }
  async create(input: CreateEventDto, actor: AuthUser) { this.validateDates(input); const event = await this.events.save(this.events.create({ ...this.clean(input), status: input.status ?? EventStatus.DRAFT, organizer: { id: actor.id } as User })); return this.detail(event.id, true); }
  async update(id: string, input: UpdateEventDto, actor: AuthUser) { const event = await this.managedEvent(id, actor); this.validateDates(input, event); const prior = event.status; Object.assign(event, this.clean(input)); const saved = await this.events.save(event); if (input.status && input.status !== prior) await this.notifyRegistrants(saved, `活动${this.statusLabel(saved.status)}`, `“${saved.title}”的状态已更新。`); return this.detail(saved.id, true); }
  async register(id: string, input: RegisterEventDto, user: AuthUser) { const event = await this.events.findOneBy({ id, status: EventStatus.PUBLISHED }); if (!event) throw new NotFoundException("活动不存在或暂不可报名"); if (event.registrationDeadline && event.registrationDeadline.getTime() < Date.now()) throw new BadRequestException("报名已截止"); if (event.startsAt.getTime() <= Date.now()) throw new BadRequestException("活动已开始，不能报名"); const existing = await this.registrations.findOne({ where: { event: { id }, user: { id: user.id } } }); if (existing && existing.status !== EventRegistrationStatus.CANCELLED) throw new ConflictException("你已报名该活动"); this.validateForm(event, input.formData ?? {}); if (event.capacity) { const count = await this.registrations.count({ where: { event: { id }, status: EventRegistrationStatus.CONFIRMED } }); if (count >= event.capacity) throw new ConflictException("活动名额已满"); }
    const registration = existing ?? this.registrations.create({ event, user: { id: user.id } as User }); registration.formData = input.formData ?? {}; registration.status = EventRegistrationStatus.PENDING; registration.checkedInAt = null; return this.registrationView(await this.registrations.save(registration)); }
  async myRegistrations(user: AuthUser) { const items = await this.registrations.find({ where: { user: { id: user.id } }, relations: { event: { organizer: true } }, order: { createdAt: "DESC" } }); return Promise.all(items.map((item) => this.registrationView(item))); }
  async registrationsForEvent(id: string, actor: AuthUser) { await this.managedEvent(id, actor); const items = await this.registrations.find({ where: { event: { id } }, relations: { user: true }, order: { createdAt: "DESC" } }); return items.map((item) => this.registrationView(item)); }
  async updateRegistration(eventId: string, registrationId: string, input: UpdateRegistrationDto, actor: AuthUser) { await this.managedEvent(eventId, actor); const registration = await this.registrations.findOne({ where: { id: registrationId, event: { id: eventId } }, relations: { event: true, user: true } }); if (!registration) throw new NotFoundException("报名记录不存在"); if (input.status !== undefined) registration.status = input.status; if (input.checkedIn !== undefined) registration.checkedInAt = input.checkedIn ? new Date() : null; const saved = await this.registrations.save(registration); if (input.status) await this.notifications.create(saved.user.id, NotificationType.EVENT_STATUS_CHANGED, "活动报名状态更新", `你报名的“${saved.event.title}”现为：${this.registrationStatusLabel(saved.status)}。`, "event", eventId); return this.registrationView(saved); }
  async exportRows(id: string, actor: AuthUser) { const items = await this.registrationsForEvent(id, actor); return items.map((item) => ({ name: item.user!.displayName, email: item.user!.email, status: item.status, checkedInAt: item.checkedInAt?.toISOString() ?? "", registeredAt: item.createdAt.toISOString(), formData: JSON.stringify(item.formData) })); }
  private async managedEvent(id: string, actor: AuthUser) { const event = await this.events.findOne({ where: { id }, relations: { organizer: true } }); if (!event) throw new NotFoundException("活动不存在"); if (!actor.roles.some((role) => ["admin", "operator", "editor"].includes(role)) && event.organizer.id !== actor.id) throw new ForbiddenException("没有活动管理权限"); return event; }
  private clean(input: Partial<CreateEventDto>) { const value: Record<string, unknown> = {}; if (input.title !== undefined) value.title = input.title.trim(); if (input.description !== undefined) value.description = input.description.trim(); if (input.locationName !== undefined) value.locationName = input.locationName.trim(); if (input.locationAddress !== undefined) value.locationAddress = input.locationAddress.trim() || null; if (input.coverUrl !== undefined) value.coverUrl = input.coverUrl || null; if (input.startsAt !== undefined) value.startsAt = new Date(input.startsAt); if (input.endsAt !== undefined) value.endsAt = new Date(input.endsAt); if (input.registrationDeadline !== undefined) value.registrationDeadline = input.registrationDeadline ? new Date(input.registrationDeadline) : null; if (input.capacity !== undefined) value.capacity = input.capacity ?? null; if (input.registrationFields !== undefined) value.registrationFields = input.registrationFields; if (input.status !== undefined) value.status = input.status; return value; }
  private validateDates(input: Partial<CreateEventDto>, current?: Event) { const start = input.startsAt ? new Date(input.startsAt) : current?.startsAt; const end = input.endsAt ? new Date(input.endsAt) : current?.endsAt; const deadline = input.registrationDeadline ? new Date(input.registrationDeadline) : current?.registrationDeadline; if (start && end && end <= start) throw new BadRequestException("结束时间必须晚于开始时间"); if (deadline && start && deadline >= start) throw new BadRequestException("报名截止时间必须早于活动开始时间"); }
  private validateForm(event: Event, data: Record<string, string>) { for (const field of event.registrationFields) if (field.required && !data[field.key]?.trim()) throw new BadRequestException(`请填写${field.label}`); }
  private async notifyRegistrants(event: Event, title: string, body: string) { const items = await this.registrations.find({ where: { event: { id: event.id }, status: EventRegistrationStatus.CONFIRMED } }); await Promise.all(items.map((item) => this.notifications.create(item.user.id, NotificationType.EVENT_STATUS_CHANGED, title, body, "event", event.id))); }
  private async view(event: Event) { const registrationCount = await this.registrations.count({ where: { event: { id: event.id }, status: EventRegistrationStatus.CONFIRMED } }); return { ...event, organizer: { id: event.organizer.id, displayName: event.organizer.displayName }, registrationCount, isRegistrationOpen: event.status === EventStatus.PUBLISHED && event.startsAt > new Date() && (!event.registrationDeadline || event.registrationDeadline > new Date()) && (!event.capacity || registrationCount < event.capacity) }; }
  private registrationView(item: EventRegistration) { return { ...item, user: item.user ? { id: item.user.id, displayName: item.user.displayName, email: item.user.email } : undefined }; }
  private statusLabel(status: EventStatus) { return ({ [EventStatus.PUBLISHED]: "已发布", [EventStatus.CANCELLED]: "已取消", [EventStatus.COMPLETED]: "已结束", [EventStatus.DRAFT]: "草稿" })[status]; }
  private registrationStatusLabel(status: EventRegistrationStatus) { return ({ pending: "待确认", confirmed: "已确认", cancelled: "已取消" })[status]; }
}
