import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { Article, ArticleStatus } from "../database/entities/article.entity";
import { Comment, CommentStatus } from "../database/entities/comment.entity";
import { Favorite, FavoriteTargetType } from "../database/entities/favorite.entity";
import { Follow, FollowTargetType } from "../database/entities/follow.entity";
import { Like, LikeTargetType } from "../database/entities/like.entity";
import { Post, PostStatus } from "../database/entities/post.entity";
import { User } from "../database/entities/user.entity";
import { Video } from "../database/entities/video.entity";
import { Creator } from "../database/entities/creator.entity";
import { MetricContentType } from "../database/entities/content-metric.entity";
import { InteractionRiskService } from "../ranking/interaction-risk.service";
import { RankingService } from "../ranking/ranking.service";

export type InteractionContext = { ip?: string; device?: string };

@Injectable()
export class InteractionsService {
  constructor(@InjectRepository(Like) private readonly likes: Repository<Like>, @InjectRepository(Favorite) private readonly favorites: Repository<Favorite>, @InjectRepository(Follow) private readonly follows: Repository<Follow>, @InjectRepository(Article) private readonly articles: Repository<Article>, @InjectRepository(Post) private readonly posts: Repository<Post>, @InjectRepository(Comment) private readonly comments: Repository<Comment>, @InjectRepository(User) private readonly users: Repository<User>, @InjectRepository(Video) private readonly videos: Repository<Video>, @InjectRepository(Creator) private readonly creators: Repository<Creator>, private readonly risk: InteractionRiskService, private readonly ranking: RankingService) {}
  async addLike(userId: string, targetType: LikeTargetType, targetId: string, context?: InteractionContext) { await this.validateContent(targetType, targetId); const check = await this.riskCheck(userId, targetType, targetId, "like", context); if (!check.allowed) return { active: false, excluded: true, reason: check.reason, count: await this.likes.count({ where: { targetType, targetId } }) }; const where = { user: { id: userId }, targetType, targetId }; const exists = await this.likes.exists({ where }); if (!exists) { await this.likes.save(this.likes.create({ user: { id: userId } as User, targetType, targetId })); await this.ranking.recordDelta(this.metricType(targetType), targetId, { likeCount: 1 }); } return { active: true, count: await this.likes.count({ where: { targetType, targetId } }) }; }
  async removeLike(userId: string, targetType: LikeTargetType, targetId: string) { const result = await this.likes.delete({ user: { id: userId }, targetType, targetId }); if (result.affected) await this.ranking.recordDelta(this.metricType(targetType), targetId, { likeCount: -1 }); return { active: false, count: await this.likes.count({ where: { targetType, targetId } }) }; }
  async addFavorite(userId: string, targetType: FavoriteTargetType, targetId: string, context?: InteractionContext) { await this.validateContent(targetType, targetId); const check = await this.riskCheck(userId, targetType, targetId, "favorite", context); if (!check.allowed) return { active: false, excluded: true, reason: check.reason, count: await this.favorites.count({ where: { targetType, targetId } }) }; const where = { user: { id: userId }, targetType, targetId }; const exists = await this.favorites.exists({ where }); if (!exists) { await this.favorites.save(this.favorites.create({ user: { id: userId } as User, targetType, targetId })); await this.ranking.recordDelta(this.metricType(targetType), targetId, { favoriteCount: 1 }); } return { active: true, count: await this.favorites.count({ where: { targetType, targetId } }) }; }
  async removeFavorite(userId: string, targetType: FavoriteTargetType, targetId: string) { const result = await this.favorites.delete({ user: { id: userId }, targetType, targetId }); if (result.affected) await this.ranking.recordDelta(this.metricType(targetType), targetId, { favoriteCount: -1 }); return { active: false, count: await this.favorites.count({ where: { targetType, targetId } }) }; }
  async addFollow(userId: string, targetType: FollowTargetType, targetId: string) { await this.validateFollow(targetType, targetId); if (targetType === FollowTargetType.USER && userId === targetId) throw new BadRequestException("不能关注自己"); const where = { follower: { id: userId }, targetType, targetId }; if (!await this.follows.exists({ where })) await this.follows.save(this.follows.create({ follower: { id: userId } as User, targetType, targetId })); return { active: true, count: await this.follows.count({ where: { targetType, targetId } }) }; }
  async removeFollow(userId: string, targetType: FollowTargetType, targetId: string) { await this.follows.delete({ follower: { id: userId }, targetType, targetId }); return { active: false, count: await this.follows.count({ where: { targetType, targetId } }) }; }
  async summary(targetType: string, targetId: string) { return { likes: await this.likes.count({ where: { targetType: targetType as LikeTargetType, targetId } }), favorites: await this.favorites.count({ where: { targetType: targetType as FavoriteTargetType, targetId } }), followers: await this.follows.count({ where: { targetType: targetType as FollowTargetType, targetId } }) }; }
  async mine(userId: string) { const [likes, favorites, follows] = await Promise.all([this.likes.find({ where: { user: { id: userId } }, order: { createdAt: "DESC" } }), this.favorites.find({ where: { user: { id: userId } }, order: { createdAt: "DESC" } }), this.follows.find({ where: { follower: { id: userId } }, order: { createdAt: "DESC" } })]); return { likes, favorites, follows }; }
  private async validateContent(targetType: LikeTargetType | FavoriteTargetType, id: string) { let exists = false; if (targetType === LikeTargetType.VIDEO) exists = await this.videos.exists({ where: { id, isPublished: true } }); else if (targetType === LikeTargetType.ARTICLE) exists = await this.articles.exists({ where: { id, status: ArticleStatus.PUBLISHED } }); else if (targetType === LikeTargetType.POST) exists = await this.posts.exists({ where: { id, status: PostStatus.PUBLISHED } }); else if (targetType === LikeTargetType.COMMENT) exists = await this.comments.exists({ where: { id, status: CommentStatus.PUBLISHED } }); if (!exists) throw new NotFoundException("互动目标不存在或不可见"); }
  private async validateFollow(targetType: FollowTargetType, id: string) { const exists = targetType === FollowTargetType.CREATOR ? await this.creators.exists({ where: { id, isEnabled: true } }) : await this.users.exists({ where: { id, isActive: true } }); if (!exists) throw new NotFoundException("关注目标不存在"); }
  private metricType(type: LikeTargetType | FavoriteTargetType) { return type === LikeTargetType.VIDEO ? MetricContentType.VIDEO : type === LikeTargetType.POST || type === LikeTargetType.COMMENT ? MetricContentType.POST : MetricContentType.ARTICLE; }
  private async riskCheck(userId: string, targetType: string, targetId: string, action: string, context?: InteractionContext) { if (!context) return { allowed: true, reason: null }; const user = await this.users.findOneBy({ id: userId }); return this.risk.inspect({ userId, targetType, targetId, action, ip: context.ip, device: context.device, accountCreatedAt: user?.createdAt }); }
}
