"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Account, refreshSession } from "../lib/auth";
import { ArticleList, ArticleStatus, ArticleType, Category, getAdminArticles, getCategories } from "../lib/content";
import { OperationsAdminNav } from "./operations-admin-nav";

const statusText: Record<ArticleStatus, string> = { draft: "草稿", review: "待审核", published: "已发布", offline: "已下线" };
const typeText: Record<ArticleType, string> = { news: "资讯", policy: "政策", insight: "深度" };
export function AdminArticles() {
  const router = useRouter(); const [user, setUser] = useState<Account | null>(null); const [data, setData] = useState<ArticleList | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [status, setStatus] = useState(""); const [type, setType] = useState(""); const [categoryId, setCategoryId] = useState(""); const [source, setSource] = useState(""); const [sourceQuery, setSourceQuery] = useState(""); const [error, setError] = useState("");
  useEffect(() => { refreshSession().then((account) => { if (!account.roles.some((role) => ["editor", "operator", "admin"].includes(role))) { setError("当前账号没有内容管理权限"); return; } setUser(account); }).catch(() => router.replace("/auth")); getCategories().then((items) => setCategories(items.flatMap((item) => [item, ...(item.children ?? [])]))).catch(() => {}); }, [router]);
  useEffect(() => { if (!user) return; setData(null); getAdminArticles({ status, type, categoryId, source: sourceQuery, limit: 30 }).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "文章加载失败")); }, [status, type, categoryId, sourceQuery, user]);
  return <main className="ops-admin-page"><OperationsAdminNav active="articles" userName={user?.displayName} /><section className="admin-shell"><div className="admin-title"><div><p className="eyebrow">CONTENT OPERATIONS</p><h1>内容工作台</h1><p>从草稿到发布，保留每一篇内容的审核状态与来源。</p></div><div className="admin-title-actions"><Link href="/admin/taxonomy">分类与标签</Link><Link className="admin-primary" href="/admin/articles/new">新建文章 <span>→</span></Link></div></div><div className="admin-filters"><label>状态<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部状态</option>{Object.entries(statusText).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>类型<select value={type} onChange={(event) => setType(event.target.value)}><option value="">全部类型</option>{Object.entries(typeText).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>分类<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">全部分类</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><form onSubmit={(event) => { event.preventDefault(); setSourceQuery(source.trim()); }}><label>来源<input value={source} onChange={(event) => setSource(event.target.value)} placeholder="输入来源名称" /></label><button type="submit">筛选</button></form></div>{error ? <p className="content-state" role="alert">{error}</p> : !data ? <p className="content-state">正在读取内容…</p> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>文章</th><th>类型</th><th>状态</th><th>分类</th><th>发布时间</th><th /></tr></thead><tbody>{data.items.map((article) => <tr key={article.id}><td><strong>{article.title}</strong><small>/{article.slug}</small></td><td>{typeText[article.type]}</td><td><span className={`status-pill ${article.status}`}>{statusText[article.status]}</span></td><td>{article.category?.name ?? "—"}</td><td>{article.publishedAt ? new Date(article.publishedAt).toLocaleDateString("zh-CN") : "—"}</td><td><Link href={`/admin/articles/${article.id}`}>编辑</Link></td></tr>)}</tbody></table>{data.items.length === 0 && <p className="content-state">没有匹配的文章。</p>}</div>}</section></main>;
}
