"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Account, refreshSession } from "../lib/auth";
import { ArticleList, ArticleStatus, ArticleType, getAdminArticles } from "../lib/content";
const statusText: Record<ArticleStatus, string> = { draft: "草稿", review: "待审核", published: "已发布", offline: "已下线" };
const typeText: Record<ArticleType, string> = { news: "资讯", policy: "政策", insight: "深度" };
export function AdminArticles() { const router = useRouter(); const [user, setUser] = useState<Account | null>(null); const [data, setData] = useState<ArticleList | null>(null); const [status, setStatus] = useState(""); const [type, setType] = useState(""); const [error, setError] = useState(""); useEffect(() => { refreshSession().then((account) => { if (!account.roles.some((role) => ["editor", "operator", "admin"].includes(role))) { setError("当前账号没有内容管理权限"); return; } setUser(account); }).catch(() => router.replace("/auth")); }, [router]); useEffect(() => { if (!user) return; getAdminArticles({ status, type, limit: 30 }).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "文章加载失败")); }, [status, type, user]); return <main className="admin-page"><header className="admin-header"><Link className="brand" href="/"><span className="brand-mark">OPC</span><span>NEXUS</span></Link><div><span>{user?.displayName ?? "内容台"}</span><Link href="/account">账户</Link></div></header><section className="admin-shell"><div className="admin-title"><div><p className="eyebrow">CONTENT OPERATIONS</p><h1>内容工作台</h1><p>从草稿到发布，保留每一篇内容的审核状态与来源。</p></div><Link className="admin-primary" href="/admin/articles/new">新建文章 <span>→</span></Link></div><div className="admin-filters"><label>状态<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部状态</option>{Object.entries(statusText).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>类型<select value={type} onChange={(event) => setType(event.target.value)}><option value="">全部类型</option>{Object.entries(typeText).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div>{error ? <p className="content-state" role="alert">{error}</p> : !data ? <p className="content-state">正在读取内容…</p> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>文章</th><th>类型</th><th>状态</th><th>分类</th><th>发布时间</th><th /></tr></thead><tbody>{data.items.map((article) => <tr key={article.id}><td><strong>{article.title}</strong><small>/{article.slug}</small></td><td>{typeText[article.type]}</td><td><span className={`status-pill ${article.status}`}>{statusText[article.status]}</span></td><td>{article.category?.name ?? "—"}</td><td>{article.publishedAt ? new Date(article.publishedAt).toLocaleDateString("zh-CN") : "—"}</td><td><Link href={`/admin/articles/${article.id}`}>编辑</Link></td></tr>)}</tbody></table>{data.items.length === 0 && <p className="content-state">没有匹配的文章。</p>}</div>}</section></main>; }
