"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Account, refreshSession } from "../lib/auth";
import { Article, ArticleType, Category, Tag, getAdminArticle, getCategories, getTags, saveArticle, transitionArticle, uploadImage } from "../lib/content";

const initial = { slug: "", title: "", summary: "", type: "news" as ArticleType, originalUrl: "", coverImageUrl: "", publishedAt: "", categoryId: "", tagIds: [] as string[], sourceName: "", sourceUrl: "", policyIssuer: "", policyNumber: "", effectiveDate: "", applicableRegion: "", policyStatus: "", policyHighlights: "", impactIndustries: "" };
type FormState = typeof initial;

export function ArticleEditor({ articleId }: { articleId?: string }) {
  const router = useRouter(); const params = useParams<{ id: string }>(); const id = articleId ?? params?.id;
  const [user, setUser] = useState<Account | null>(null); const [article, setArticle] = useState<Article | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [tags, setTags] = useState<Tag[]>([]); const [form, setForm] = useState<FormState>(initial); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [uploading, setUploading] = useState(false);
  const canPublish = Boolean(user?.roles.some((role) => ["operator", "admin"].includes(role)));

  useEffect(() => {
    refreshSession().then((account) => { if (!account.roles.some((role) => ["editor", "operator", "admin"].includes(role))) { setError("当前账号没有内容管理权限"); return; } setUser(account); }).catch(() => router.replace("/auth"));
    getCategories().then((items) => setCategories(items.flatMap((item) => [item, ...(item.children ?? [])]))).catch(() => setError("分类加载失败"));
    getTags().then(setTags).catch(() => setError("标签加载失败"));
  }, [router]);
  useEffect(() => {
    if (!id || !user) return;
    getAdminArticle(id).then((value) => { const source = value.sources.find((item) => item.isPrimary) ?? value.sources[0]; setArticle(value); setForm({ slug: value.slug, title: value.title, summary: value.summary, type: value.type, originalUrl: value.originalUrl, coverImageUrl: value.coverImageUrl ?? "", publishedAt: value.publishedAt ? value.publishedAt.slice(0, 16) : "", categoryId: value.category?.id ?? "", tagIds: value.tags.map((tag) => tag.id), sourceName: source?.name ?? "", sourceUrl: source?.url ?? "", policyIssuer: value.policyIssuer ?? "", policyNumber: value.policyNumber ?? "", effectiveDate: value.effectiveDate ?? "", applicableRegion: value.applicableRegion ?? "", policyStatus: value.policyStatus ?? "", policyHighlights: value.policyHighlights ?? "", impactIndustries: value.impactIndustries ?? "" }); }).catch((reason) => setError(reason instanceof Error ? reason.message : "文章加载失败"));
  }, [id, user]);

  function setField<K extends keyof FormState>(key: K, value: FormState[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(""); try { const result = await uploadImage(file); setField("coverImageUrl", result.url); setMessage("首图已上传，请保存文章。"); } catch (reason) { setError(reason instanceof Error ? reason.message : "图片上传失败"); } finally { setUploading(false); event.target.value = ""; } }
  async function submit(event: FormEvent) {
    event.preventDefault(); setError(""); setMessage("");
    try {
      const payload: Record<string, unknown> = { slug: form.slug, title: form.title, summary: form.summary, type: form.type, originalUrl: form.originalUrl, coverImageUrl: form.coverImageUrl || undefined, publishedAt: form.publishedAt ? new Date(form.publishedAt).toISOString() : id ? null : undefined, categoryId: form.categoryId || undefined, tagIds: form.tagIds, sources: form.sourceName && form.sourceUrl ? [{ name: form.sourceName, url: form.sourceUrl, isPrimary: true }] : [] };
      if (form.type === "policy") Object.assign(payload, { policyIssuer: form.policyIssuer || (id ? null : undefined), policyNumber: form.policyNumber || (id ? null : undefined), effectiveDate: form.effectiveDate || (id ? null : undefined), applicableRegion: form.applicableRegion || (id ? null : undefined), policyStatus: form.policyStatus || (id ? null : undefined), policyHighlights: form.policyHighlights || (id ? null : undefined), impactIndustries: form.impactIndustries || (id ? null : undefined) });
      const saved = await saveArticle(id ?? null, payload); setArticle(saved); setMessage("草稿已保存。"); if (!id) router.replace(`/admin/articles/${saved.id}`);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "未能保存文章"); }
  }
  async function action(value: "submit" | "publish" | "offline" | "return" | "restore") { if (!article) return; setError(""); try { const saved = await transitionArticle(article.id, value); setArticle(saved); setMessage({ submit: "已提交审核。", publish: "文章已发布。", offline: "文章已下线。", return: "已退回草稿。", restore: "已恢复为草稿。" }[value]); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作未完成"); } }
  const policy = form.type === "policy";

  return <main className="editor-page"><header className="admin-header"><Link className="brand" href="/admin/articles"><span className="brand-mark">OPC</span><span>NEXUS</span></Link><Link href="/admin/articles">返回工作台</Link></header><section className="editor-shell"><div className="editor-heading"><div><p className="eyebrow">{article ? "EDIT ARTICLE" : "NEW ARTICLE"}</p><h1>{article ? "编辑内容" : "新建内容"}</h1></div>{article && <div className="editor-actions"><span className={`status-pill ${article.status}`}>{article.status === "draft" ? "草稿" : article.status === "review" ? "待审核" : article.status === "published" ? "已发布" : "已下线"}</span><Link href={`/admin/articles/${article.id}/preview`}>预览</Link>{article.status === "draft" && <button onClick={() => action("submit")}>提交审核</button>}{article.status === "review" && canPublish && <><button onClick={() => action("return")}>退回修改</button><button onClick={() => action("publish")}>审核并发布</button></>}{article.status === "published" && canPublish && <button onClick={() => action("offline")}>下线</button>}{article.status === "offline" && canPublish && <button onClick={() => action("restore")}>恢复草稿</button>}</div>}</div>
    <form className="editor-form" onSubmit={submit}><div className="editor-main"><label>内容类型<select value={form.type} onChange={(event) => setField("type", event.target.value as ArticleType)}><option value="news">资讯</option><option value="policy">政策</option><option value="insight">深度文章</option></select></label><label>标题<input required value={form.title} onChange={(event) => setField("title", event.target.value)} maxLength={240} /></label><label>摘要<textarea required value={form.summary} onChange={(event) => setField("summary", event.target.value)} rows={6} maxLength={800} /></label><div className="two-fields"><label>Slug<input required value={form.slug} onChange={(event) => setField("slug", event.target.value)} pattern="[a-z0-9-]+" /></label><label>分类<select value={form.categoryId} onChange={(event) => setField("categoryId", event.target.value)}><option value="">未分类</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label></div><div className="two-fields"><label>原文链接<input required type="url" value={form.originalUrl} onChange={(event) => setField("originalUrl", event.target.value)} /></label><label>计划发布时间<input type="datetime-local" value={form.publishedAt} onChange={(event) => setField("publishedAt", event.target.value)} /></label></div><label>封面图片链接<input type="url" value={form.coverImageUrl} onChange={(event) => setField("coverImageUrl", event.target.value)} /></label><label className="upload-field">或上传首图<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading} /><span>{uploading ? "正在上传…" : "JPG / PNG / WebP，最大 5MB"}</span></label>{form.coverImageUrl && <img className="cover-preview" src={form.coverImageUrl} alt="首图预览" />}<fieldset><legend>标签</legend><div className="tag-checks">{tags.map((tag) => <label key={tag.id}><input type="checkbox" checked={form.tagIds.includes(tag.id)} onChange={(event) => setField("tagIds", event.target.checked ? [...form.tagIds, tag.id] : form.tagIds.filter((value) => value !== tag.id))} />{tag.name}</label>)}</div></fieldset>
      {policy && <fieldset className="policy-editor"><legend>政策字段</legend><div className="two-fields"><label>发文机关<input value={form.policyIssuer} onChange={(event) => setField("policyIssuer", event.target.value)} /></label><label>文号<input value={form.policyNumber} onChange={(event) => setField("policyNumber", event.target.value)} /></label><label>生效日期<input type="date" value={form.effectiveDate} onChange={(event) => setField("effectiveDate", event.target.value)} /></label><label>适用地域<input value={form.applicableRegion} onChange={(event) => setField("applicableRegion", event.target.value)} /></label><label>政策状态<input value={form.policyStatus} onChange={(event) => setField("policyStatus", event.target.value)} /></label></div><label>政策要点<textarea value={form.policyHighlights} onChange={(event) => setField("policyHighlights", event.target.value)} rows={4} /></label><label>影响行业<textarea value={form.impactIndustries} onChange={(event) => setField("impactIndustries", event.target.value)} rows={3} /></label></fieldset>}</div>
      <aside className="editor-aside"><p className="eyebrow">SOURCE</p><h2>主要来源</h2><label>来源名称<input value={form.sourceName} onChange={(event) => setField("sourceName", event.target.value)} placeholder="例如：国务院" /></label><label>来源链接<input type="url" value={form.sourceUrl} onChange={(event) => setField("sourceUrl", event.target.value)} placeholder="https://…" /></label><p>文章公开页会明确标注来源，并引导读者回到原文。</p></aside>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}<button className="admin-primary" type="submit" disabled={uploading}>保存草稿 <span>→</span></button></form></section></main>;
}
