"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ForumPostList, ForumSection, getForumPosts, getForumSections } from "../lib/forum";

export function CommunityIndex() {
  const [sections, setSections] = useState<ForumSection[]>([]); const [data, setData] = useState<ForumPostList | null>(null); const [section, setSection] = useState(""); const [sort, setSort] = useState<"latest" | "hot" | "featured">("latest"); const [page, setPage] = useState(1); const [error, setError] = useState("");
  useEffect(() => { getForumSections().then(setSections).catch((reason) => setError(reason instanceof Error ? reason.message : "板块加载失败")); }, []);
  useEffect(() => { setData(null); setError(""); getForumPosts({ section, sort, page }).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "帖子加载失败")); }, [section, sort, page]);
  return <main className="community-page"><section className="community-hero"><div><p className="eyebrow">OPC PROFESSIONAL FORUM</p><h1>把判断放到<br />同行之间</h1></div><div className="community-manifesto"><p>围绕财经、产业与经营问题展开可追溯的专业讨论。观点可以不同，证据需要清楚。</p><Link href="/community/new">发起讨论 <span>→</span></Link></div></section><section className="community-shell"><aside className="section-rail"><button className={!section ? "active" : ""} onClick={() => { setSection(""); setPage(1); }}><span>全部讨论</span><b>{sections.reduce((sum, item) => sum + (item.postCount ?? 0), 0)}</b></button>{sections.map((item) => <button className={section === item.slug ? "active" : ""} onClick={() => { setSection(item.slug); setPage(1); }} key={item.id}><span>{item.name}<small>{item.description}</small></span><b>{item.postCount ?? 0}</b></button>)}</aside><section className="discussion-feed"><header><div><p className="eyebrow">DISCUSSION LEDGER</p><h2>{section ? sections.find((item) => item.slug === section)?.name : "最新讨论"}</h2></div><div className="feed-sort"><button className={sort === "latest" ? "active" : ""} onClick={() => setSort("latest")}>最新</button><button className={sort === "hot" ? "active" : ""} onClick={() => setSort("hot")}>热门</button><button className={sort === "featured" ? "active" : ""} onClick={() => setSort("featured")}>精华</button></div></header>{error ? <p className="content-state" role="alert">{error}</p> : !data ? <p className="content-state">正在连接讨论现场…</p> : data.items.length ? <>{data.items.map((post) => <article className="discussion-card" key={post.id}><div className="discussion-flags">{post.isPinned && <span>置顶</span>}{post.isFeatured && <span>精华</span>}<span>{post.section.name}</span></div><h3><Link href={`/community/posts/${post.id}`}>{post.title}</Link></h3><p>{post.body}</p><footer><span>{post.author.displayName}{post.author.jobTitle ? ` · ${post.author.jobTitle}` : ""}</span><span>{new Date(post.createdAt).toLocaleDateString("zh-CN")}</span><span>{post.viewCount} 阅读 · {post.commentCount} 回复</span></footer></article>)}<nav className="pagination"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>上一页</button><span>第 {page} / {data.pagination.totalPages || 1} 页</span><button disabled={page >= data.pagination.totalPages} onClick={() => setPage((value) => value + 1)}>下一页</button></nav></> : <p className="content-state">这个板块还没有讨论。你可以发起第一篇。</p>}</section></section></main>;
}
