"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Account, refreshSession } from "../lib/auth";
import { CrawlAuthorizationStatus, CrawlFetchMethod, CrawlSource, CrawlSourceInput, CrawlSourceType, createCrawlSource, getCrawlSources, runCrawlNow, updateCrawlSource } from "../lib/crawler";
import { OperationsAdminNav } from "./operations-admin-nav";
import styles from "./crawl-manager.module.css";

const blank: CrawlSourceInput = { name: "", domain: "", type: "news", fetchMethod: "rss", authorizationStatus: "pending", isEnabled: false, autoPublish: false, entryUrl: "" };
const sourceTypeLabels: Record<CrawlSourceType, string> = { news: "资讯", policy: "政策", video: "视频", rss: "RSS 资讯", sitemap: "站点地图" };
const fetchMethodLabels: Record<CrawlFetchMethod, string> = { html: "HTML 页面", rss: "RSS / Atom", sitemap: "XML Sitemap", adapter: "专用适配器" };
const authorizationLabels: Record<CrawlAuthorizationStatus, string> = { pending: "待确认", authorized: "已授权", restricted: "受限", rejected: "拒绝" };

export function CrawlManager() {
  const router = useRouter(); const [user, setUser] = useState<Account | null>(null); const [sources, setSources] = useState<CrawlSource[]>([]); const [form, setForm] = useState<CrawlSourceInput>(blank); const [editingId, setEditingId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [runningId, setRunningId] = useState<string | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { setLoading(true); try { setSources(await getCrawlSources()); } catch (reason) { setError(reason instanceof Error ? reason.message : "无法读取采集来源"); } finally { setLoading(false); } }
  useEffect(() => { refreshSession().then((account) => { if (!account.roles.some((role) => ["editor", "operator", "admin"].includes(role))) throw new Error("没有采集配置权限"); setUser(account); return load(); }).catch(() => router.replace("/auth")); }, [router]);
  function edit(source: CrawlSource) { setEditingId(source.id); setForm({ name: source.name, domain: source.domain, type: source.type, fetchMethod: source.fetchMethod, authorizationStatus: source.authorizationStatus, isEnabled: source.isEnabled, autoPublish: source.autoPublish, entryUrl: source.entryUrl ?? "" }); setMessage(""); setError(""); }
  function reset() { setEditingId(null); setForm(blank); setError(""); setMessage(""); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { const input = { ...form, entryUrl: form.entryUrl?.trim() || undefined }; if (editingId) await updateCrawlSource(editingId, input); else await createCrawlSource(input); await load(); setMessage(editingId ? "来源配置已更新。" : "来源已保存；授权并启用后才会被每日任务采集。"); reset(); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } finally { setSaving(false); } }
  async function run(source?: CrawlSource) { if (source && (!source.isEnabled || source.authorizationStatus !== "authorized")) return; setRunningId(source?.id ?? "all"); setError(""); setMessage(""); try { const result = await runCrawlNow(source?.id); const totals = result.runs.reduce((value, current) => ({ articles: value.articles + current.articles, videos: value.videos + current.videos, duplicates: value.duplicates + current.duplicates, filtered: value.filtered + current.filtered, warnings: value.warnings + current.warnings }), { articles: 0, videos: 0, duplicates: 0, filtered: 0, warnings: 0 }); setMessage(`本次完成 ${result.sourceCount} 个来源：新增 ${totals.articles} 篇文章、${totals.videos} 个视频，智能体过滤 ${totals.filtered} 条，去重 ${totals.duplicates} 条${totals.warnings ? `，${totals.warnings} 条待检查` : ""}。`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "采集任务没有完成"); } finally { setRunningId(null); } }
  const set = <K extends keyof CrawlSourceInput>(key: K, value: CrawlSourceInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  return <main className="ops-admin-page"><OperationsAdminNav active="crawler" userName={user?.displayName} /><div className="ops-admin-shell">
    <section className="ops-title"><div><p className="eyebrow">SOURCE CONTROL DESK</p><h1>每日内容采集</h1><p>只从已取得授权的来源采集标题、摘要、封面与原链接。新闻和政策默认进入审核；开启自动发布后才会出现在公开频道。</p></div><button className={styles.runAll} type="button" onClick={() => void run()} disabled={runningId !== null || !sources.some((source) => source.isEnabled && source.authorizationStatus === "authorized")}>{runningId === "all" ? "正在采集…" : "立即采集全部已启用来源"}</button></section>
    {error && <p className="ops-error" role="alert">{error}</p>}{message && <p className="ops-success" role="status">{message}</p>}
    <section className="config-workbench crawl-workbench"><form onSubmit={save}><header><div><p>{editingId ? "EDIT SOURCE" : "NEW SOURCE"}</p><h2>{editingId ? "编辑来源" : "添加来源"}</h2></div>{editingId && <button type="button" onClick={reset}>取消编辑</button>}</header><div className="config-form-grid"><label className="wide">来源名称<input required maxLength={160} value={form.name} onChange={(event) => set("name", event.target.value)} placeholder="例如：某政府部门政策公开栏" /></label><label>内容类型<select value={form.type} onChange={(event) => set("type", event.target.value as CrawlSourceType)}>{Object.entries(sourceTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>抓取方式<select value={form.fetchMethod} onChange={(event) => set("fetchMethod", event.target.value as CrawlFetchMethod)}>{Object.entries(fetchMethodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>来源域名<input required value={form.domain} onChange={(event) => set("domain", event.target.value)} placeholder="example.gov.cn" /></label><label>授权状态<select value={form.authorizationStatus} onChange={(event) => set("authorizationStatus", event.target.value as CrawlAuthorizationStatus)}>{Object.entries(authorizationLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="wide">入口地址<input type="url" value={form.entryUrl} onChange={(event) => set("entryUrl", event.target.value)} placeholder="https://example.gov.cn/feed.xml" /></label><label className="config-online"><input type="checkbox" checked={form.isEnabled} onChange={(event) => set("isEnabled", event.target.checked)} /><span>启用每日采集（仅已授权来源可保存为启用）</span></label>{form.type !== "video" && <label className="config-online"><input type="checkbox" checked={form.autoPublish} onChange={(event) => set("autoPublish", event.target.checked)} /><span>审核通过授权后自动发布到公开频道</span></label>}</div><button className="ops-primary" disabled={saving}><span>{saving ? "正在保存…" : editingId ? "保存来源" : "添加来源"}</span><span>→</span></button></form><aside><p className="eyebrow">DAILY ROUTINE</p><h2>采集守则</h2><ol><li><b>01</b><span>确认版权、robots 规则和来源授权，再标记为“已授权”。</span></li><li><b>02</b><span>每天按服务器配置的时间运行；可用“立即采集”验证。</span></li><li><b>03</b><span>系统按链接和正文指纹去重，并保留原文链接。</span></li><li><b>04</b><span>未开启自动发布的新闻与政策进入审核队列，不会直接公开。</span></li></ol><p>视频频道只展示受权来源的视频元数据与原链接，不下载或转载视频本体。</p></aside></section>
    <section className="config-registry crawl-registry"><header><div><p className="eyebrow">AUTHORIZED SOURCE REGISTRY</p><h2>来源与采集记录</h2></div><span>{sources.length} 个来源</span></header>{loading ? <p className="ops-state">正在读取来源…</p> : <div className="config-table-wrap"><table><thead><tr><th>来源</th><th>内容</th><th>授权 / 状态</th><th>展示方式</th><th>最近采集</th><th /></tr></thead><tbody>{sources.map((source) => <tr key={source.id}><td><strong>{source.name}</strong><small>{source.domain}{source.entryUrl ? ` · ${source.entryUrl}` : ""}</small></td><td>{sourceTypeLabels[source.type]}<small>{fetchMethodLabels[source.fetchMethod]}</small></td><td><span className={`config-status ${source.authorizationStatus === "authorized" && source.isEnabled ? "live" : "scheduled"}`}>{authorizationLabels[source.authorizationStatus]}</span><small>{source.isEnabled ? "已启用" : "未启用"}</small></td><td>{source.type === "video" ? "视频元数据" : source.autoPublish ? "自动发布" : "进入审核"}</td><td>{source.lastCrawledAt ? new Date(source.lastCrawledAt).toLocaleString("zh-CN", { dateStyle: "medium", timeStyle: "short" }) : "尚未采集"}</td><td><button type="button" onClick={() => edit(source)}>编辑</button><button type="button" onClick={() => void run(source)} disabled={runningId !== null || !source.isEnabled || source.authorizationStatus !== "authorized"}>{runningId === source.id ? "采集中…" : "立即采集"}</button></td></tr>)}</tbody></table>{sources.length === 0 && <p className="ops-state">还没有采集来源。添加并授权来源后，每日任务才会开始工作。</p>}</div>}</section>
  </div></main>;
}
