"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { FeedItem, getFeed } from "../lib/ranking";

const modes = [{ value: "recommended", label: "为你推荐" }, { value: "latest", label: "最新" }, { value: "hot", label: "热度" }, { value: "following", label: "关注" }];
const labels: Record<FeedItem["contentType"], string> = { article: "资讯", policy: "政策", video: "视频", post: "社区", demand: "需求" };
export function DiscoveryFeed() {
  const [mode, setMode] = useState("recommended"); const [items, setItems] = useState<FeedItem[]>([]); const [industry, setIndustry] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); setError(""); getFeed(mode, "all", industry).then(setItems).catch((reason) => setError(reason instanceof Error ? reason.message : "信息流加载失败")).finally(() => setLoading(false)); }, [mode, industry]);
  return <main className="signal-feed"><header className="signal-feed-hero"><div><p className="eyebrow">OPC SIGNAL LEDGER</p><h1>今天，什么值得<br /><span>继续判断。</span></h1></div><aside><p>资讯、政策、视频与社区讨论进入同一套热度口径；每条推荐都说明原因。</p><Link href="/rankings">查看全站热榜 →</Link></aside></header><section className="signal-toolbar" aria-label="信息流筛选"><div>{modes.map((item) => <button className={mode === item.value ? "active" : ""} onClick={() => setMode(item.value)} key={item.value}>{item.label}</button>)}</div><label>行业偏好<input value={industry} onChange={(event) => setIndustry(event.target.value)} placeholder="例如：人工智能" /></label></section>{error && <p className="content-state" role="alert">{error}</p>}{loading ? <p className="content-state">正在计算推荐…</p> : <div className="signal-layout"><section className="signal-list">{items.map((item) => <article key={`${item.contentType}-${item.id}`}><div className="signal-reason">{item.reason}</div><div className="signal-type">{labels[item.contentType]}<span>{item.industry ?? "综合"}</span></div><div><h2>{item.contentType === "video" ? <a href={item.url} target="_blank" rel="noreferrer">{item.title}</a> : <Link href={item.url}>{item.title}</Link>}</h2><p>{item.excerpt}</p><footer><span>{item.source} · {new Date(item.publishedAt).toLocaleDateString("zh-CN")}</span><span>热度 {item.heat.toFixed(1)}</span></footer></div></article>)}{!items.length && <p className="content-state">当前筛选下还没有内容。</p>}</section><aside className="signal-method"><p className="eyebrow">HOW IT READS</p><h2>热度不是音量。</h2><p>互动经过异常过滤，跨平台指标使用百分位归一化，再考虑时间、主题匹配和来源可信度。</p><dl><div><dt>01</dt><dd>站内真实互动</dd></div><div><dt>02</dt><dd>跨平台标准化</dd></div><div><dt>03</dt><dd>时间与质量修正</dd></div></dl></aside></div>}</main>;
}
