"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Event, createEvent, getManagedEvents, updateEvent } from "../lib/forum";
import { refreshSession } from "../lib/auth";

type Form = { title: string; description: string; locationName: string; locationAddress: string; startsAt: string; endsAt: string; registrationDeadline: string; capacity: string; status: "draft" | "published" | "cancelled" | "completed" };
const empty: Form = { title: "", description: "", locationName: "", locationAddress: "", startsAt: "", endsAt: "", registrationDeadline: "", capacity: "", status: "draft" };
const localValue = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";
function toForm(event: Event): Form { return { title: event.title, description: event.description, locationName: event.locationName, locationAddress: event.locationAddress ?? "", startsAt: localValue(event.startsAt), endsAt: localValue(event.endsAt), registrationDeadline: localValue(event.registrationDeadline), capacity: event.capacity?.toString() ?? "", status: event.status }; }

export function EventEditor({ id }: { id?: string }) {
  const router = useRouter(); const [form, setForm] = useState<Form>(empty); const [message, setMessage] = useState(""); const [ready, setReady] = useState(!id); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!id) return; refreshSession().then(getManagedEvents).then(({ items }) => { const event = items.find((item) => item.id === id); if (!event) throw new Error("找不到活动，或你没有管理权限。"); setForm(toForm(event)); setReady(true); }).catch((error) => setMessage(error instanceof Error ? error.message : "活动加载失败")); }, [id]);
  function update<K extends keyof Form>(key: K, value: Form[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); try { const payload = { ...form, startsAt: new Date(form.startsAt).toISOString(), endsAt: new Date(form.endsAt).toISOString(), registrationDeadline: form.registrationDeadline ? new Date(form.registrationDeadline).toISOString() : undefined, capacity: form.capacity ? Number(form.capacity) : undefined }; const saved = id ? await updateEvent(id, payload) : await createEvent(payload); router.replace(`/admin/events/${saved.id}/edit`); setMessage("活动已保存。"); } catch (error) { setMessage(error instanceof Error ? error.message : "活动未能保存，请检查必填项和时间。 "); } finally { setSaving(false); } }
  if (!ready) return <main className="event-editor"><p className="content-state">{message || "正在读取活动…"}</p></main>;
  return <main className="event-editor"><header><div><p className="eyebrow">OPERATIONS / EVENT BRIEF</p><h1>{id ? "编辑活动" : "创建活动"}</h1><p>先确定时间、地点和容量；发布前可保留为草稿。</p></div><Link href="/admin/events">返回活动管理</Link></header><form onSubmit={(event) => void save(event)}><div className="event-editor-fields"><label>活动名称<input required maxLength={160} value={form.title} onChange={(event) => update("title", event.target.value)} /></label><label>状态<select value={form.status} onChange={(event) => update("status", event.target.value as Form["status"])}><option value="draft">草稿</option><option value="published">发布</option><option value="cancelled">取消</option><option value="completed">已结束</option></select></label><label>开始时间<input required type="datetime-local" value={form.startsAt} onChange={(event) => update("startsAt", event.target.value)} /></label><label>结束时间<input required type="datetime-local" value={form.endsAt} onChange={(event) => update("endsAt", event.target.value)} /></label><label>报名截止时间<input type="datetime-local" value={form.registrationDeadline} onChange={(event) => update("registrationDeadline", event.target.value)} /></label><label>人数上限<input min="1" type="number" value={form.capacity} onChange={(event) => update("capacity", event.target.value)} placeholder="不设上限" /></label><label>活动地点<input required maxLength={160} value={form.locationName} onChange={(event) => update("locationName", event.target.value)} /></label><label>详细地址<input maxLength={280} value={form.locationAddress} onChange={(event) => update("locationAddress", event.target.value)} placeholder="可选" /></label><label className="wide">活动说明<textarea required maxLength={12000} value={form.description} onChange={(event) => update("description", event.target.value)} rows={10} /></label></div><footer><span>{message}</span><button disabled={saving}>{saving ? "正在保存…" : "保存活动"}</button></footer></form></main>;
}
