"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { refreshSession } from "../lib/auth";
import { ForumSection, getForumSections, getOwnPost, saveForumPost } from "../lib/forum";

export function ForumPostEditor({ edit = false }: { edit?: boolean }) {
  const router = useRouter(); const params = useParams<{ id: string }>(); const id = edit ? params.id : null; const [sections, setSections] = useState<ForumSection[]>([]); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [sectionId, setSectionId] = useState(""); const [status, setStatus] = useState<"draft" | "published">("published"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { refreshSession().then(() => getForumSections()).then((values) => { setSections(values); if (!id) setSectionId(values[0]?.id ?? ""); }).catch(() => router.replace("/auth")); }, [id, router]);
  useEffect(() => { if (!id) return; getOwnPost(id).then((post) => { setTitle(post.title); setBody(post.body); setSectionId(post.section.id); setStatus(post.status === "draft" ? "draft" : "published"); }).catch((reason) => setError(reason instanceof Error ? reason.message : "帖子加载失败")); }, [id]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const post = await saveForumPost(id, { title, body, sectionId, status }); if (post.status === "published") router.push(`/community/posts/${post.id}`); else { setError(""); router.replace(`/community/posts/${post.id}/edit`); } } catch (reason) { setError(reason instanceof Error ? reason.message : "帖子未能保存"); } finally { setSaving(false); } }
  return <main className="forum-compose"><header><Link className="brand" href="/community"><span className="brand-mark">OPC</span><span>NEXUS</span></Link><Link href="/community">退出编辑</Link></header><form onSubmit={submit}><div className="compose-heading"><p className="eyebrow">{edit ? "REVISE DISCUSSION" : "START A DISCUSSION"}</p><h1>{edit ? "编辑讨论" : "发起讨论"}</h1><p>先说清问题，再给出背景、判断依据和你期待同行回应的部分。</p></div><label>讨论标题<input required minLength={4} maxLength={180} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="一个具体、可讨论的问题" /></label><label>正文<textarea required minLength={10} maxLength={30000} rows={16} value={body} onChange={(event) => setBody(event.target.value)} placeholder="背景是什么？你观察到了什么？哪些判断还需要验证？" /></label><div className="compose-meta"><label>板块<select required value={sectionId} onChange={(event) => setSectionId(event.target.value)}>{sections.map((section) => <option value={section.id} key={section.id}>{section.name}</option>)}</select></label><label>保存方式<select value={status} onChange={(event) => setStatus(event.target.value as "draft" | "published")}><option value="published">直接发布</option><option value="draft">保存草稿</option></select></label></div>{error && <p className="form-error" role="alert">{error}</p>}<button className="compose-submit" disabled={saving}>{saving ? "正在保存…" : status === "draft" ? "保存草稿" : "发布讨论"}<span>→</span></button></form></main>;
}
