"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Account, refreshSession } from "../lib/auth";
import { Report, getReports, resolveReport } from "../lib/forum";

export function ModerationManager() {
  const router = useRouter(); const [account, setAccount] = useState<Account | null>(null); const [reports, setReports] = useState<Report[]>([]); const [status, setStatus] = useState("pending"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  async function load(value = status) { setLoading(true); try { setReports((await getReports(value)).items); } catch (reason) { setError(reason instanceof Error ? reason.message : "举报队列加载失败"); } finally { setLoading(false); } }
  useEffect(() => { refreshSession().then((value) => { if (!value.roles.some((role) => ["moderator", "operator", "admin"].includes(role))) throw new Error("没有审核权限"); setAccount(value); return load(); }).catch(() => router.replace("/auth")); }, [router]);
  async function act(report: Report, mode: "resolve" | "reject") { const resolution = window.prompt(mode === "reject" ? "说明驳回原因" : "填写处置说明"); if (!resolution) return; const action = mode === "reject" ? "none" : report.targetType === "user" ? "ban" : "hide"; try { await resolveReport(report.id, { status: mode === "reject" ? "rejected" : "resolved", action, resolution }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "处理失败"); } }
  function targetLink(report: Report) { if (report.targetType === "post") return `/community/posts/${report.targetId}`; if (report.targetType === "comment" && report.targetPreview?.postId) return `/community/posts/${report.targetPreview.postId}`; if (report.targetType === "article") return `/admin/articles/${report.targetId}/preview`; if (report.targetType === "demand") return `/demands/${report.targetId}`; return null; }
  return <main className="moderation-page"><header className="admin-header"><Link className="brand" href="/"><span className="brand-mark">OPC</span><span>NEXUS</span></Link><div><span>{account?.displayName ?? "审核台"}</span><Link href="/community">查看社区</Link></div></header><section className="moderation-shell"><div className="admin-title"><div><p className="eyebrow">TRUST &amp; SAFETY DESK</p><h1>举报审核</h1><p>先核对上下文，再执行隐藏、封禁或驳回；每次处置都会留下记录。</p></div></div><div className="moderation-tabs">{["pending", "resolved", "rejected"].map((value) => <button className={status === value ? "active" : ""} onClick={() => { setStatus(value); void load(value); }} key={value}>{value === "pending" ? "待处理" : value === "resolved" ? "已处理" : "已驳回"}</button>)}</div>{error && <p className="form-error" role="alert">{error}</p>}{loading ? <p className="content-state">正在读取举报队列…</p> : <div className="report-queue">{reports.map((report) => <article key={report.id}><div className="report-code">{report.targetType.toUpperCase()}<span>{report.id.slice(0, 8)}</span></div><div><h2>{report.reason}</h2>{report.targetPreview && <div className="target-preview"><strong>{report.targetPreview.title}</strong><p>{report.targetPreview.excerpt || "无公开资料"}</p></div>}<p>{report.details || "举报人未补充说明。"}</p><footer>举报人 {report.reporter.displayName} · {new Date(report.createdAt).toLocaleString("zh-CN")}</footer></div><div className="report-actions">{targetLink(report) && <Link href={targetLink(report)!}>查看目标</Link>}{status === "pending" && <><button onClick={() => act(report, "reject")}>驳回</button><button className="danger" onClick={() => act(report, "resolve")}>{report.targetType === "user" ? "封禁用户" : "隐藏内容"}</button></>}</div></article>)}{reports.length === 0 && <p className="content-state">当前队列为空。</p>}</div>}</section></main>;
}
