"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Category, SearchResponse, getCategories, searchContent } from "../lib/content";
import { ForumSection, getForumSections } from "../lib/forum";

export function SearchPage() {
  const [query, setQuery] = useState(""); const [type, setType] = useState("all"); const [source, setSource] = useState(""); const [category, setCategory] = useState(""); const [categories, setCategories] = useState<Category[]>([]); const [sections, setSections] = useState<ForumSection[]>([]); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [page, setPage] = useState(1); const [data, setData] = useState<SearchResponse | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { getCategories().then((items) => setCategories(items.flatMap((item) => [item, ...(item.children ?? [])]))).catch(() => {}); getForumSections().then(setSections).catch(() => {}); }, []);
  async function run(nextPage = 1) { if (!query.trim()) return; setLoading(true); setError(""); try { setData(await searchContent({ q: query.trim(), type, category, source, from, to, page: nextPage })); setPage(nextPage); } catch (reason) { setError(reason instanceof Error ? reason.message : "搜索失败"); } finally { setLoading(false); } }
  function submit(event: FormEvent) { event.preventDefault(); void run(1); }
  return <main className="search-page"><section className="search-hero"><p className="eyebrow">OPC KNOWLEDGE INDEX</p><h1>搜索行业信号</h1><form onSubmit={submit}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="政策、公司、行业或关键词" aria-label="搜索关键词" required /><button disabled={loading}>{loading ? "检索中…" : "搜索"}</button></form></section><section className="search-shell"><div className="search-filters"><label>内容类型<select value={type} onChange={(event) => setType(event.target.value)}><option value="all">全部</option><option value="article">文章</option><option value="post">社区帖子</option><option value="video">视频</option></select></label><label>分类或板块<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">全部分类</option><optgroup label="内容分类">{categories.map((item) => <option value={item.slug} key={item.id}>{item.name}</option>)}</optgroup><optgroup label="社区板块">{sections.map((item) => <option value={item.slug} key={item.id}>{item.name}</option>)}</optgroup></select></label><label>来源 / 作者<input value={source} onChange={(event) => setSource(event.target.value)} placeholder="例如：国务院" /></label><label>开始日期<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>结束日期<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label></div>{error && <p className="content-state" role="alert">{error}</p>}{data && <><div className="search-summary">找到 {data.pagination.total} 条结果</div><div className="search-results">{data.items.map((item) => <article key={`${item.contentType}-${item.id}`}><span>{item.contentType === "article" ? "文章" : item.contentType === "post" ? "社区" : "视频"} · {item.category ?? item.subtype}</span><h2><Link href={item.url}>{item.title}</Link></h2><p>{item.excerpt}</p><footer>{item.source ?? "OPC Nexus"}{item.publishedAt ? ` · ${new Date(item.publishedAt).toLocaleDateString("zh-CN")}` : ""}</footer></article>)}</div>{data.items.length === 0 && <p className="content-state">没有找到匹配内容，试试更短的关键词。</p>}<nav className="pagination"><button disabled={page <= 1} onClick={() => run(page - 1)}>上一页</button><span>第 {page} / {data.pagination.totalPages || 1} 页</span><button disabled={page >= data.pagination.totalPages} onClick={() => run(page + 1)}>下一页</button></nav></>}</section></main>;
}
