"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { refreshSession } from "../lib/auth";
import { Category, Tag, createCategory, createTag, deleteCategory, deleteTag, getAdminCategories, getTags, updateCategory } from "../lib/content";

export function TaxonomyManager() {
  const router = useRouter(); const [categories, setCategories] = useState<Category[]>([]); const [tags, setTags] = useState<Tag[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { const [categoryValues, tagValues] = await Promise.all([getAdminCategories(), getTags()]); setCategories(categoryValues.flatMap((item) => [item, ...(item.children ?? [])])); setTags(tagValues); }
  useEffect(() => { refreshSession().then((account) => { if (!account.roles.some((role) => ["editor", "operator", "admin"].includes(role))) throw new Error(); return load(); }).catch(() => router.replace("/auth")); }, [router]);
  async function create(event: FormEvent<HTMLFormElement>, kind: "category" | "tag") { event.preventDefault(); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); try { if (kind === "category") await createCategory({ name: data.name, slug: data.slug, sortOrder: Number(data.sortOrder || 0), parentId: data.parentId || undefined }); else await createTag({ name: data.name, slug: data.slug }); event.currentTarget.reset(); await load(); setMessage(kind === "category" ? "分类已创建。" : "标签已创建。"); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } }
  async function toggle(category: Category) { setError(""); try { await updateCategory(category.id, { isActive: !category.isActive }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "更新失败"); } }
  async function remove(kind: "category" | "tag", id: string) { if (!window.confirm("确认删除？此操作不能撤销。")) return; setError(""); try { if (kind === "category") await deleteCategory(id); else await deleteTag(id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "删除失败"); } }
  return <main className="admin-page"><header className="admin-header"><Link className="brand" href="/admin/articles"><span className="brand-mark">OPC</span><span>NEXUS</span></Link><Link href="/admin/articles">返回内容工作台</Link></header><section className="admin-shell"><div className="admin-title"><div><p className="eyebrow">CONTENT TAXONOMY</p><h1>分类与标签</h1><p>让每一条行业信息进入清晰、稳定的内容结构。</p></div></div>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}<div className="taxonomy-grid"><section><h2>分类</h2><form className="taxonomy-form" onSubmit={(event) => create(event, "category")}><input name="name" required placeholder="分类名称" maxLength={80} /><input name="slug" required placeholder="category-slug" pattern="[a-z0-9-]+" /><input name="sortOrder" type="number" min="0" defaultValue="0" aria-label="排序" /><select name="parentId" aria-label="父分类"><option value="">顶级分类</option>{categories.filter((item) => !categories.some((parent) => parent.children?.some((child) => child.id === item.id))).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><button>创建分类</button></form><div className="taxonomy-list">{categories.map((category) => <div key={category.id}><span><strong>{category.name}</strong><small>{category.slug} · 排序 {category.sortOrder ?? 0}</small></span><button onClick={() => toggle(category)}>{category.isActive === false ? "启用" : "停用"}</button><button onClick={() => remove("category", category.id)}>删除</button></div>)}</div></section><section><h2>标签</h2><form className="taxonomy-form" onSubmit={(event) => create(event, "tag")}><input name="name" required placeholder="标签名称" maxLength={80} /><input name="slug" required placeholder="tag-slug" pattern="[a-z0-9-]+" /><button>创建标签</button></form><div className="taxonomy-list">{tags.map((tag) => <div key={tag.id}><span><strong>{tag.name}</strong><small>{tag.slug}</small></span><button onClick={() => remove("tag", tag.id)}>删除</button></div>)}</div></section></div></section></main>;
}
